In [ ]:
import numpy as np

In [ ]:
def unit_vec(vector):
  mu = np.linalg.norm(vector)
  return vector / mu

In [ ]:
unit_vec(np.array([0,1,0]))

array([0., 1., 0.])

In [ ]:
unit_vec(np.array([5,3,2]))

array([0.81110711, 0.48666426, 0.32444284])

In [ ]:
def vec(vector, mag):
  mu = np.linalg.norm(vector)
  return mag * vector / mu

In [ ]:
v = np.array([[1,2,3]])
vt = np.zeros((3,1))

for i in range(v.shape[1]):
    vt[i, 0] = v[0, i]

vt

array([[1.],
       [2.],
       [3.]])

In [ ]:
# aTb = bTa # Коммутативный закон

np.dot([1,2,3], [4,5,6]) == np.dot([4,5,6], [1,2,3],) # висящая запятая


True

In [ ]:
n = 11

a = np.random.randn(n,1) # row / column
b = np.random.randn(n,1)

aTb = np.sum(a*b)
bTa = np.sum(b*a)

aTb - bTa

# help(np.random.randn)


0.0

In [ ]:
V = {v1,...,Vn} # множетсво векторов



In [ ]:
# Линейная комбинация  / взвешенная / линейная смесь

w = λ1*v1 + λ2*v2+...+λnvn  # Линейная комбинация - умножение вектора на скаляр и сложение
# vi - одинаковая размерность, λ любое действиетельное число включая ноль
# Сложение векторов только равной размерности!


In [ ]:
λ1 = 1, λ2 = 2, λ3 = 3

v1 = [1,2,3] # [1,2,3]
v2 = [4,5,6] # [8,10,12]
v3 = [3,1,5] # [9,3,15]

w = λ1*v1 + λ2*v2+...+λnvn = [18,15,30]


Множество векторов является **линейно зависимым**, если по меньшей мере один вектор в множетве можно выразить как линейную комбинацию, других векторов в этом множестве

И следовательно множество является **линейно независимым**, если ни один вектор нельзя выразить как линейную комбинацию

In [ ]:
# V = {[1,3],[2,7]} # unhashable
V = {(1,3),(2,7)} # линейно независимые, невозможно подобрать скаляр
V2 = {(1,3),(2,6)} # линейно зависимые
v1 = λv2


{(1, 3), (2, 7)}

In [ ]:
# Линейная зависимость векторов
a1 * x1+ a2*x2+..+an*xn = 0
# Если равенство выполняется при ai, не все из которых =0, то такая система векторов x1, x2, ..., xn называется линейно зависисмой.


Лининейные(векторные) пространства:
Расстомтрим такое {x} на котром ведем=определеим 2 операции:
* сложение элементов
*  умножение элемента на число(R).
При совершении любой из этих операций элемент останется в данном {x}.


Если выполняются аксиомы, которые определены ниже, то такое

 мн-во наз-ся линейным пространством!

* если элементы линейного пространства - векторы, то данное пространство  ЛИНЕНЙНО-ВЕКТОРНОЕ
*

Аксиома линейного(-векторного) пространства:


1.   элементы ЛП коммутативны: a + b=b+a; a,b belongs X
2.   сложение эл-тов ассоциативно: a + (b+c) = (a+b)+c ; a,b,c belongs X
3.   мно-во X содержит 0-элемент  для которого: a+0=a; a brlongs X   
4.  В мно-ве  X для любого эл-та существует обратный элемнет, те a & (-a). При этом выполняется a + (-a)=0; a, (-a) belongs X
5.    Произвдение суммы элементов из множества X на число РАВНО сумме произведений этого числа на данные элементы. q*(a+b)=q*a+q*b;a,b belongs X & q belongs R
6. Произведение суммы чисел на элемент множества Х РАВНО сумме произведений элемента на заданные числа: (q+p)*a=q*a+p*a; a belongs X & p, q belong R
7.   Произведение чисел умноженное на элемент из множества Х РАВНО произведению одного из чисел и элемента, умноженного на другое число.
(q*p)*a = q*(p*a); a belongs X & p, q belong R
8. Множество Х содержит единичный элемент для которго справедливо равенство 1*a = a; a belongs X, 1 - scalar
